language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "1.0"
  - "2.0"
  - "3.0"
  - "4.0"
  - "4.x"
  - "5.0"
  - "5.x"
notifications:
  email:
    on_success: never
script: "npm run-script test-cov"
after_script: "cat ./coverage/lcov.info | coveralls"
