language: node_js
sudo: false
node_js:
  - "0.10"
  - "0.12"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"
notifications:
  email:
    on_success: never
script: "npm run-script test-cov"
after_script: "cat ./coverage/lcov.info | coveralls"
