environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "1.0"
    - nodejs_version: "2.0"
    - nodejs_version: "3.0"
    - nodejs_version: "4.0"
    - nodejs_version: "4.x"
    - nodejs_version: "5.0"
    - nodejs_version: "5.x"
install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - npm install
build: off
test_script:
  - node --version
  - npm --version
  - npm test
